services:
  db:
    image: postgres:16-bookworm
    container_name: cp-office-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Docker managed volume as doesn't start with ./ or /
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cp_bot_user -d cp_office_bot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: