export const COMPLAINT_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  IN_REVIEW: "IN_REVIEW",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
} as const;

export type ComplaintStatus =
  (typeof COMPLAINT_STATUSES)[keyof typeof COMPLAINT_STATUSES];

export const COMPLAINT_LOCATION_SOURCES = {
  MANUAL_TEXT: "MANUAL_TEXT",
  WHATSAPP_LOCATION: "WHATSAPP_LOCATION",
  WHATSAPP_LIVE_LOCATION: "WHATSAPP_LIVE_LOCATION",
  UNKNOWN: "UNKNOWN",
} as const;

export type ComplaintLocationSource =
  (typeof COMPLAINT_LOCATION_SOURCES)[keyof typeof COMPLAINT_LOCATION_SOURCES];

export const COMPLAINT_MEDIA_KINDS = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  AUDIO: "AUDIO",
  DOCUMENT: "DOCUMENT",
  ID_PROOF: "ID_PROOF",
  OTHER: "OTHER",
} as const;

export type ComplaintMediaKind =
  (typeof COMPLAINT_MEDIA_KINDS)[keyof typeof COMPLAINT_MEDIA_KINDS];

export const COMPLAINT_STATUS_UPDATED_BY_TYPES = {
  SYSTEM: "SYSTEM",
  OFFICER: "OFFICER",
} as const;

export type ComplaintStatusUpdatedByType =
  (typeof COMPLAINT_STATUS_UPDATED_BY_TYPES)[keyof typeof COMPLAINT_STATUS_UPDATED_BY_TYPES];

export const COMPLAINT_FLOW_STEPS = {
  SELECT_POLICE_STATION_METHOD: "SELECT_POLICE_STATION_METHOD",
  SELECT_POLICE_STATION: "SELECT_POLICE_STATION",

  COLLECT_FULL_NAME: "COLLECT_FULL_NAME",
  COLLECT_PHONE: "COLLECT_PHONE",

  COLLECT_ID_PROOF_TYPE: "COLLECT_ID_PROOF_TYPE",
  COLLECT_ID_PROOF_NUMBER: "COLLECT_ID_PROOF_NUMBER",

  COLLECT_CATEGORY: "COLLECT_CATEGORY",
  COLLECT_DESCRIPTION: "COLLECT_DESCRIPTION",

  COLLECT_LOCATION: "COLLECT_LOCATION",
  COLLECT_MEDIA: "COLLECT_MEDIA",

  CONFIRM_SUBMISSION: "CONFIRM_SUBMISSION",
} as const;

export type ComplaintFlowStep =
  (typeof COMPLAINT_FLOW_STEPS)[keyof typeof COMPLAINT_FLOW_STEPS];

  export const POLICE_STATION_SELECTION_METHODS = {
  CHOOSE_FROM_LIST: "CHOOSE_FROM_LIST",
  USE_NEAREST: "USE_NEAREST",
  TYPE_NAME: "TYPE_NAME",
  NOT_SURE: "NOT_SURE",
} as const;

export type PoliceStationSelectionMethod =
  (typeof POLICE_STATION_SELECTION_METHODS)[keyof typeof POLICE_STATION_SELECTION_METHODS];