
export const INTENTS = {
  FILE_COMPLAINT: "FILE_COMPLAINT",
  CHECK_COMPLAINT_STATUS: "CHECK_COMPLAINT_STATUS",
  FIND_POLICE_STATION: "FIND_POLICE_STATION",
  FIND_PARKING: "FIND_PARKING",
  GENERAL_QNA: "GENERAL_QNA",
  UNKNOWN: "UNKNOWN",
} as const;

export type Intent = (typeof INTENTS)[keyof typeof INTENTS];