
export const SESSION_STATES = {
  WAITING_FOR_LANGUAGE: "WAITING_FOR_LANGUAGE",
  READY: "READY",
  IN_COMPLAINT_FLOW: "IN_COMPLAINT_FLOW",
  CHECKING_COMPLAINT_STATUS: "CHECKING_COMPLAINT_STATUS",
  ENDED: "ENDED",
} as const;

export type SessionState =
  (typeof SESSION_STATES)[keyof typeof SESSION_STATES];

